Repository haddocking/deeprank-gnn-esm, pull requests merged in 2025-03, with the labels that each got.

#7 update `pyproject.toml`
  pyproject.toml
Labels: repository

#10 update `README.md`
  README.md
Labels: repository

#1 add dockerfile
  Dockerfile
Labels: enhancement, repository

#13 Update api
  src/deeprank_gnn/DataSet.py
  src/deeprank_gnn/GraphGenMP.py
  src/deeprank_gnn/community_pooling.py
  src/deeprank_gnn/predict.py
Labels: enhancement
